# Generated by Django 4.2.5 on 2023-09-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0002_ad_genre_movie_playlist_user_adgenre_moviegenre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdGenre',
        ),
    ]
