# Generated by Django 4.2.5 on 2023-09-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0003_delete_adgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
