# Generated by Django 4.2.5 on 2023-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0004_delete_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('viewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(unique=True)),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'viewer',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='playlistmovies',
            name='id_movie',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='PlaylistMovies',
        ),
    ]
